### ISSUE TITLE
mvn install failed

### ISSUE THREAD

**Issue by fluet** [Qordobacode/api-sdk-java#2]
I followed the instruction but mvn install failed:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project QordobaLib: Compilation failure: Compilation failure:
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[1483,16] error: method getTmAsync(String,APICallBack<LinkedHashMap<String,Object>>) is already defined in class QordobaController
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[1557,16] error: method getTmAsync(String,APICallBack<LinkedHashMap<String,Object>>) is already defined in class QordobaController
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[1630,16] error: method createTmAsync(APICallBack<Object>) is already defined in class QordobaController
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[2185,16] error: method getGlossariesAsync(String,APICallBack<LinkedHashMap<String,Object>>) is already defined in class QordobaController
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[2259,16] error: method getGlossariesAsync(String,APICallBack<LinkedHashMap<String,Object>>) is already defined in class QordobaController
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[2409,16] error: method createGlossariesAsync(APICallBack<Object>) is already defined in class QordobaController
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[2472,16] error: method getGlossariesAsync(String,String,APICallBack<LinkedHashMap<String,Object>>) is already defined in class QordobaController
[ERROR] /private/var/tmp/testing/api-sdk-java/QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:[2758,16] error: method getLanguagesAsync(APICallBack<LinkedHashMap<String,Object>>) is already defined in class QordobaController
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wassemgtk** [comment]
Your Maven is reading Java version as 1.6.XX, Where as the pom.xml says the version is 1.7.

Try installing the required verison.

If already installed check your $JAVA_HOME environment variable, it should contain the path of Java JDK 7. If you dont find it, fix your environment variable.

try
mvn clean install -X helps to identify the root cause.

Some of the important phases of Maven build lifecycle are:

clean – the project is clean of all artifacts that came from previous compilations compile – the project is compiled into /target directory of project root install – packaged archive is copied into local maven repository (could in your user's home directory under /.m2) test – unit tests are run package – compiled sources are packaged into archive (JAR by default)

**Comment by fluet** [comment]
You sure I'm using 1.6.XX? Here is output of "java -version":

$ java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

Are you able to repeat the issue?

**Comment by wassemgtk** [comment]
Hi @fluent - we haven’t been able to reproduce that error. Can you send me your Skype ID to waseem AT qordoba dot com? Happy to help you debug live.

**Comment by fluet** [comment]
I don't have Skype account.

If you look at the error message, the method has defined more than once in QordobaLib/src/com/qordoba/developers/controllers/QordobaController.java:

    public void getTmAsync(
            final String tmId,
            final APICallBack<LinkedHashMap<String, Object>> callBack
    ) {

How can you get around the issue?

**Comment by wassemgtk** [comment]
Can you send me your email to waseem AT qordoba dot com? Happy to help you debug live. I will Send you video conference URL.

**Comment by fluet** [comment]
Thanks for the prompt reply but unfortunately we won't go any further as my colleagues also got similar errors about duplicated method signature with the Java SDK. Earlier I tried the C# SDK but got a lot of errors as well.

**Comment by wassemgtk** [comment]
Strange. There may be a missing installation steps. In any case, it’s not going to work without keys. Happy to give you test keys on the phone on Monday. Email me a number and happy to call you.
